version: '2.1'

services:
  jb-service:
    image: jb-service
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3002:3002
      - 9229:9229
    ## set your startup file here
    command: node --inspect index.js